os: Visual Studio 2019
version: "{branch}-{build}"

branches:
 only:
  - master
  - beta
  - rc
  - /try-.*/
  # For tags, branch = tag if GitHub couldn't work out the base branch.
  - /release-.*/
  
environment:
 PY_PYTHON: 3.7-32
 secure_authenticode_pass:
  secure: Way+hJyhbiLG/cmCo4+dHHzS5DiSvk/45o6frnIQ27GBX6nVDsh7jwQ7fSnqxBRP
 secure_ssh_pass:
  secure: ekOvuyywHuDdGZmRmoj+b3jfrq39A2xlx4RD5ZUGd/8=
 mozillaSymsAuthToken:
  secure: p37Fxo78fsRdmR8v8TPz978QvVaqvbjdIBzFe8ZOpX0FUprm46rkhd374QM1CqMO
 symstore: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symstore.exe

init:
 - ps: |

install:
 - cd appveyor
 # Decrypt files.
 - ps: |
 - type ssh_known_hosts >> %userprofile%\.ssh\known_hosts
 - cd ..
 - git submodule update --init

build_script:
 - ps: |
 - 'echo scons args: %sconsArgs%'
 - scons source %sconsArgs%
 - if ERRORLEVEL 1 exit %ERRORLEVEL%
 # We don't need launcher to run checkPot, so run the checkPot before launcher.
 - ps: |
 # The pot gets built by tests, but we don't actually need it as a build artifact.
 - 'echo scons output targets: %sconsOutTargets%'
 - scons %sconsOutTargets% %sconsArgs%
 - if ERRORLEVEL 1 exit %ERRORLEVEL%
 # Build symbol store.
 - ps: |
 - cd symbols
 - 7z a -tzip -r ..\output\symbols.zip *.dl_ *.ex_ *.pd_
 - if ERRORLEVEL 1 exit %ERRORLEVEL%
 - cd ..

before_test:
 - mkdir testOutput
 - mkdir testOutput\unit
 - mkdir testOutput\system
 - mkdir testOutput\lint
 - ps: |

test_script:
# Unit Tests (Python)
 - ps: |

# Flake8 Linting
 - ps: |

# System tests
 - ps: |

after_test:
 # fail build if any tests failed
 - ps: |

# Artifacts are required by deploy code,
artifacts:
  - path: output\*
  - path: output\*\*

# Still upload artifacts on failure, they are useful for testing PR builds despite the build perhaps
# failing for a minor reason (eg linting)
on_failure:
#  `- path` is not allowed in `on_failure` use powerShell instead
 - ps: |

# The server side deploy code ('nvdaAppveyorHook') relies on artifacts, they must be uploaded first.
# For ordering of appveyor yml phases, see: https://www.appveyor.com/docs/build-configuration/#build-pipeline
deploy_script:
 - ps: |

on_finish:
  # add a message to point to the NVDA build, to make testing PR's easier.
  - ps: |
